version: '3'
services:
  data_warehouse_hotel_db:
    image: postgres:latest
    container_name: data_warehouse
    restart: always
    environment:
      - POSTGRES_DB= etl_test_result
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5434:5432 